VERSION = "1.0.0"
MONGO_CONNECTION_STRING = "mongodb+srv://antoniocastaldo:Respublica96.@unior-mtpe.mbhsh.mongodb.net/?retryWrites=true&w=majority&appName=unior-mtpe"
ADMIN_EMAIL = "ancastal@outlook.it"
ADMIN_PASSWORD = "Respublica96."

# Supabase credentials for default free database
PROJECT_URL = "https://xlsmdqmkdknjkhteajqu.supabase.co"
PROJECT_API_KEY = "sb_publishable_TlrZMgaiXF33LUB_VIdqTA_RzoHRkcu"

[client]
toolbarMode = "minimal"
[ui]
hideTopBar = true
